// Writes src/server/slack-emoji-names.ts from emoji-datasource's emoji.json (ADR 0042).
//
//   npm pack emoji-datasource@<version> && tar xzf emoji-datasource-<version>.tgz
//   node scripts/slack-emoji-names.ts package/emoji.json <version>
//
// emoji-datasource (iamcal/emoji-data, MIT License, Copyright (c) 2013 Cal Henderson) names each emoji the way Slack
// does. Only the names are kept: the package itself is too large to ship for one lookup.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const [source, version] = process.argv.slice(2);
if (!source || !version) {
  console.error('usage: node scripts/slack-emoji-names.ts <emoji.json> <emoji-datasource version>');
  process.exit(2);
}

interface Entry { short_names: string[]; skin_variations?: Record<string, unknown> }
const entries = JSON.parse(readFileSync(source, 'utf8')) as Entry[];
const names = new Set<string>();
const toned = new Set<string>();
for (const entry of entries) {
  for (const name of entry.short_names) names.add(name);
  // One tone for the whole emoji (`::skin-tone-2` to `-6`); the two-person emoji that take two tones are left out.
  if (Object.keys(entry.skin_variations ?? {}).some(key => !key.includes('-'))) for (const name of entry.short_names) toned.add(name);
}

const list = (set: Set<string>) => [...set].sort().map(name => `  ${JSON.stringify(name)},`).join('\n');
const target = fileURLToPath(new URL('../src/server/slack-emoji-names.ts', import.meta.url));
writeFileSync(target, `// Generated by scripts/slack-emoji-names.ts from emoji-datasource ${version}; do not edit.
// emoji-datasource (https://github.com/iamcal/emoji-data): MIT License, Copyright (c) 2013 Cal Henderson.

/** Every standard emoji's names as Slack knows them, without colons. */
export const STANDARD_EMOJI: readonly string[] = [
${list(names)}
];

/** The standard emoji that take a skin tone, \`<name>::skin-tone-2\` to \`-6\`. */
export const TONED_EMOJI: readonly string[] = [
${list(toned)}
];
`);
console.log(`${names.size} names, ${toned.size} take a skin tone`);
